### PR TITLE
4.0.0 Migration

### PR DESCRIPTION
**Pull request by jonafanho**
Things to note:

* I had to remove some Russian comments from the `Blocks` class because the build couldn't recognise non-UTF-8 characters for some reason.
* I was able to load up the mod in 1.20.4 Fabric and Forge, but I haven't done any testing regarding block/item functionality

### CODE REVIEW

**Review by WerySkok — APPROVED** [review]
Changes LGTM to me, now I need to test it in game

**Review by WerySkok — COMMENTED** [review]
The results of playtest:

- New ticket barriers are not transparent
- Old ticket barriers create a new block of themselves when passing by
- Info-SOS is facing the opposite side while placing
- Weird render issues with metro emblem block изображение
- "Horizontal lift" doors do not appear in game

**Comment by Kenny-Hui** [comment]
I've encountered the UTF-8 issue as well in JCM, seems to vary between systems
See if this helps:
https://github.com/DistrictOfJoban/Joban-Client-Mod/blob/31ea38b8ed58280be3ca90fe20c39cb97042958c/build.gradle#L49-L51

**Comment by WerySkok** [comment]
Ok, so now everything should work (including "horizontal lift"), so merging

**Pull request merged**
